### ISSUE TITLE
Can't download latest data file

### ISSUE THREAD

**Issue by cbetta** [mackuba/holepicker#10]
I am getting this error:

```
Can't download latest data file: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by mackuba** [comment]
This sounds like an OpenSSL problem with your local Ruby installation, I
had a lot of those recently too... Which Ruby are you running, on what OS,
how did you install it?

**Comment by cbetta** [comment]
Ruby 2.0 on OS X 10.8. I will give it a try to fix it because it indeed does work on my other machine

**Comment by mackuba** [comment]
I've tried to install 1.9.3 and 2.0 from rvm recently on my new computer and I had ssl errors too... I think what finally fixed them was getting the very latest head rvm and letting it install things the way it wants (with autolibs 3, so that it can install openssl, gcc etc. via brew). And I've also installed curl-ca-bundle package.
