### ISSUE TITLE
Add option to only give output when vulnerable gems are found

### ISSUE THREAD

**Issue by RaymiiOrg** [mackuba/holepicker#8]
I'm trying to write a holepicker / nagios check. I now use the following grep rule:

~$ holepicker -f /etc/nginx/sites-enabled | grep -v -e OK -e Looking -e Fetching -e "No vulnerabilities" -e "✔"

But this is not always working, sometimes it gives other output and sometimes it just fails without errors.

Would it be possible to add an option (--silent for example) which would only give output when vulnerable gems are found? 

Also, a --compact or --summary option which would only give the number of vulnerable gems (or 0 if none found) would be helpfull for integrating holepicker in nagios.

**Comment by mackuba** [comment]
Holepicker should return status 0 if there are no vulnerabilities and non-zero if it finds any, is that enough for you?

**Comment by RaymiiOrg** [comment]
Yes that helps. Would a compact mode as suggested be possible?

**Comment by steveyken** [comment]
This would be very interesting... would you be willing to share that nagios
check when you're done?

**Comment by mackuba** [comment]
@RaymiiOrg: I'll see what I can do.

**Comment by timocp** [comment]
I use a simple wrapper script to get this effect:

``` sh
#! /bin/sh
output=/tmp/holes-$$.txt
if ! /opt/ruby/bin/holepicker -o -c /location/of/apps > $output; then
  cat $output
fi
rm $output
```

This is suitable to run from cron, where you really only want output when something is wrong.  But it would be nice to have something like this built in.

**Comment by mackuba** [comment]
I'm not convinced about the "print number of issues" mode, because I'm not sure what that number should be: number of gemfiles with bad gems? Total number of bad gems? Or maybe number of unique bad gems across gemfiles? (And you've got pretty much the same thing printed in the summary line below the gemfile results.)

I like the idea of a "silent" mode though. I've replaced all `print`/`puts` with calls to a shared logger, so it's now easy to manage them globally. Check out the latest version - `-s` should set the logger level to ERROR, and there's also a `--no-color` option that disables coloring. Is this enough for you?

**Comment by RaymiiOrg** [comment]
For the first part, if you have the time to implement it, give the option to list each one individually (f.e. --list-bad-gemfiles, --list-unique-bad-gems etc).

I'm now going to see if the version works :+1:

**Comment by RaymiiOrg** [comment]
I read it wrong, I thought with the `-s` option you would send output to STDERR, but it only shows the non-info logging. 

```
125 vulnerable gems found in 19 gemfiles!
```

But still, I think I can work with this :+1:
